---
# SPDX-FileCopyrightText: 2025-2026  IMAGIN sp. z o.o.
# SPDX-FileContributor: Marcin Engelmann <mengelmann@octivi.com>
# SPDX-License-Identifier: MIT
#
# This file is part of the configuration created by Octivi's DevOps team.
# Details at https://octivi.com/devops

name: Update Copyright Year
description: Update copyright years in file headers based on provided sed regexps.
branding:
  icon: calendar
  color: blue
inputs:
  targets:
    description: "Directories to scan (space-separated), e.g. '. src scripts'"
    required: false
    default: "."
  exclude_paths:
    description: "Paths to exclude (space-separated), e.g. '.github/workflows build'"
    required: false
    default: ".github/workflows"
  include_glob:
    description: "Optional glob patterns to include (space-separated), e.g. '**/*.{sh,py,js}'"
    required: false
    default: ""
  organization_regexp:
    description: "Optional regexp snippet for the organization/person name after the year (used only when headers_regexp is empty)."
    required: false
    default: ""
  headers_regexp:
    description: "Array of sed regexps (one per line). Use {{CURRENT_YEAR}} as a placeholder. Leave empty to use the built-in default (optionally constrained by organization_regexp)."
    required: false
    default: ""
runs:
  using: composite
  steps:
    - name: Update year in headers
      shell: bash
      env:
        TARGETS: ${{ inputs.targets }}
        EXCLUDE_PATHS: ${{ inputs.exclude_paths }}
        INCLUDE_GLOB: ${{ inputs.include_glob }}
        ORGANIZATION_REGEXP: ${{ inputs.organization_regexp }}
        HEADERS_REGEXP: ${{ inputs.headers_regexp }}
      run: ${{ github.action_path }}/update-copyright-year
